### ISSUE TITLE
Can you provide the exported pb file or the output node name?

### ISSUE THREAD

**Issue by JustinhoCHN** [markgao-916/yolov3_fire_detection#1]
Thanks for your work, I want to export the model to the pb file, need the output node name, I've tried "output_node_names = ['conv_sbbox', 'conv_mbbox', 'conv_lbbox']", but always exited with error: "AssertionError: conv_sbbox is not in graph".

My export code is:

```
import tensorflow as tf
from tensorflow.python.framework import graph_util

input_checkpoint = './checkpoint/yolov3_test_loss=3.2609.ckpt-43'
output_graph = './pb_checkpoint/yolov3_test_loss=3.2609.ckpt-43.pb'
output_node_names = ['pred_sbbox/conv_sbbox', 'conv_mbbox', 'conv_lbbox']
saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=True)

with tf.Session() as sess:
    saver.restore(sess, input_checkpoint) 
    output_graph_def = graph_util.convert_variables_to_constants(
        sess=sess,
        input_graph_def=sess.graph_def,
        output_node_names=output_node_names)

    with tf.gfile.GFile(output_graph, "wb") as f: 
        f.write(output_graph_def.SerializeToString()) 
    print("%d ops in the final graph." % len(output_graph_def.node))
```

Can you provide the exported pb file or the output node name?

PS: I've checked the output node name via tensorboard, it shows  ['conv_sbbox', 'conv_mbbox', 'conv_lbbox'].

**Comment by JustinhoCHN** [comment]
@markgao-916 hi mark, can you please check this issue?

**Comment by markgao-916** [comment]
I am sorry to say i have not do this work, but this work refer to[https://github.com/YunYang1994/tensorflow-yolov3](url), you can check from the origin work.

**Comment by JustinhoCHN** [comment]
sorry, I missed the frozen_graph.py, it can export the pb file. Thanks mark! @markgao-916
